baseURL = "https://aws.danthesalmon.com"
languageCode = "en-us"
title = "Dan [the] Salmon"
theme = "pixyll"

contentdir = "content"
publishdir = "public"


builddrafts = false
canonifyurls = true
author = "admin"


[indexes]
  category = "categories"
  tag = "tags"

[params]
 
  google_analytics_id = "XX-XXXXXXXX-X"
  twitter_username = "username"
  disqus_shortname = "sitename"
  paginate = true