author = "admin"
baseURL = "https://danthesalmon.com"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-us"
publishdir = "public"
theme = "pixyll"
title = "Dan [the] Salmon"
[indexes]
category = "categories"
tag = "tags"
[params]
 
google_analytics_id = "XX-XXXXXXXX-X"
twitter_username = "bltjetpack"
disqus_shortname = "danthesalmon"
paginate = true
