---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: danthesalmon.com/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: danthesalmon.com/content/images
  label: Images
  create: all
  match: "**/*"
upload_dir: danthesalmon.com/content/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.39'
